AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hello-world-lambda
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: ./src
      MemorySize: 128
      Timeout: 5
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get
